# Generated by Django 5.0.6 on 2024-07-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebrg', models.CharField(max_length=5)),
                ('merk', models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo'), ('Realme', 'Realme')], default='Xiaomi', max_length=20)),
                ('tipe', models.CharField(max_length=20)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=20)),
                ('ket', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Termurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebrg', models.CharField(max_length=5)),
                ('merk', models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo'), ('Realme', 'Realme')], default='Xiaomi', max_length=20)),
                ('tipe', models.CharField(max_length=20)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodebrg', models.CharField(max_length=5)),
                ('tipe', models.CharField(max_length=20)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('merk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.merk')),
            ],
        ),
    ]
