# Generated by Django 5.0.6 on 2024-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
