# Generated by Django 5.0.6 on 2024-07-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_produk_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='gambar',
        ),
        migrations.AddField(
            model_name='hotsale',
            name='link_gambar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='produk',
            name='link_gambar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='termurah',
            name='link_gambar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
