# Generated by Django 5.0.6 on 2024-07-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_produk_gambar_hotsale_link_gambar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotsale',
            old_name='harga',
            new_name='hargah',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='kodebrg',
            new_name='kodebrgh',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='link_gambar',
            new_name='link_gambarh',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='merk',
            new_name='merkh',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='stok',
            new_name='stokh',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='tipe',
            new_name='tipeh',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='harga',
            new_name='hargat',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='kodebrg',
            new_name='kodebrgt',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='link_gambar',
            new_name='link_gambart',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='merk',
            new_name='merkt',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='stok',
            new_name='stokt',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='tipe',
            new_name='tipet',
        ),
    ]
