# Generated by Django 5.0.6 on 2024-07-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_harga_hotsale_hargah_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotsale',
            old_name='kodebrgh',
            new_name='kode_produk_hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='merkh',
            new_name='merk_produk_hotsale',
        ),
    ]
