# Generated by Django 5.0.6 on 2024-07-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_kodebrgh_hotsale_kode_produk_hotsale_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merk',
            new_name='Merkp',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='hargah',
            new_name='harga_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='kode_produk_hotsale',
            new_name='kode_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='link_gambarh',
            new_name='link_Gambar_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='merk_produk_hotsale',
            new_name='merk_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='stokh',
            new_name='stok_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='hotsale',
            old_name='tipeh',
            new_name='tipe_Produk_Hotsale',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='harga',
            new_name='harga_Produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='kodebrg',
            new_name='kode_Produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='link_gambar',
            new_name='link_Gambar_Produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='merk_id',
            new_name='merk_Produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='stok',
            new_name='stok_Produk',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='tipe',
            new_name='tipe_Produk',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='hargat',
            new_name='harga_Produk_Termurah',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='kodebrgt',
            new_name='kode_Produk_Termurah',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='link_gambart',
            new_name='link_Gambar_Produk_Termurah',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='merkt',
            new_name='merk_Produk_Termurah',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='stokt',
            new_name='stok_Produk_Termurah',
        ),
        migrations.RenameField(
            model_name='termurah',
            old_name='tipet',
            new_name='tipe_Produk_Termurah',
        ),
    ]
